# Slate Dashboard - Widget Layout
# ===============================
# Flat structure where each widget is top-level

# HEADER ROW - Logo and Clock
slate-logo:
  type: "widget"
  widget: "image"
  position:
    row: 1
    column: 1
    span: 2
  backgroundColor: "linear-gradient(135deg, rgba(255, 255, 255, 0.95) 0%, rgba(59, 130, 246, 0.2) 100%)"
  config:
    src: "slate_logo_821_286.png"
    alt: "Slate Logo"
    height: "60px"
    objectFit: "contain"
    className: "logo-widget"

header-clock:
  type: "widget"
  widget: "clock"
  position:
    row: 1
    column: 10
    span: 3
  config:
    format: "12h"
    showDate: true

# GROUPS (containers only - no items)
dev-group:
  type: "group"
  title: "Development"
  position:
    row: 2
    column: 1
    span: 6
  collapsible: true
  collapsed: false
  backgroundColor: "#1a365d"

services-group:
  type: "group"
  title: "Services"
  position:
    row: 2
    column: 7
    span: 6
  collapsible: true
  collapsed: false

# WIDGETS IN DEV GROUP
github-link:
  type: "link"
  group: "dev-group"
  name: "GitHub"
  url: "https://github.com"
  icon: "github"
  description: "Code repository"
  statusCheck: false

gitlab-link:
  type: "link"
  group: "dev-group"
  name: "GitLab"
  url: "https://gitlab.com"
  icon: "gitlab"
  description: "Alternative Git hosting"
  statusCheck: false

dev-obsidian:
  type: "obsidian"
  group: "dev-group"
  config:
    vaultPath: "/Users/paul/Library/Mobile Documents/iCloud~md~obsidian/Documents/Vault42/"
    tag: "dev"
    namespace: "dashboard"
    maxNotes: 2

# WIDGETS IN SERVICES GROUP
docker-link:
  type: "link"
  group: "services-group"
  name: "Docker Hub"
  url: "https://hub.docker.com"
  icon: "docker"
  description: "Container registry"
  statusCheck: false

prometheus-link:
  type: "link"
  group: "services-group"
  name: "Prometheus"
  url: "http://localhost:9090"
  icon: "prometheus"
  description: "Monitoring system"
  statusCheck: false

search-group:
  type: "group"
  title: "Search & Discovery"
  position:
    row: 3
    column: 1
    span: 8
  collapsible: true
  collapsed: false

# WIDGETS IN SEARCH GROUP
searchxng-link:
  type: "link"
  group: "search-group"
  name: "SearchXNG"
  url: "https://searchxng.squirrel-corn.ts.net"
  icon: "search"
  description: "Private Search Engine"
  statusCheck: true

testing-notes:
  type: "motd"
  group: "search-group"
  title: "Testing Notes"
  message: "need to test SearchXNG on Obsidian vs. the MCP"
  icon: "🔬"
  priority: "normal"
  dismissible: true
  timestamp: true

search-todoist:
  type: "todoist"
  group: "search-group"
  config:
    apiToken: "2f8731b4a8938ae6ea67d44cfe57fb1d08da604d"
    projectName: "Dashboard"
    tag: "search"
    maxTasks: 3

search-trilium:
  type: "trilium"
  group: "search-group"
  config:
    tag: "dashboard_search"
    maxNotes: 2

weather-widget:
  type: "widget"
  widget: "weather"
  position:
    row: 3
    column: 9
    span: 4
  backgroundColor: "#0f4c75"
  config:
    location: "30033"
    displayName: "Decatur, GA"
    units: "fahrenheit"
    apiKey: "a8ef47eaa6bec9780dad5ad07c880c61"

data-group:
  type: "group"
  title: "Data & Storage"
  position:
    row: 4
    column: 1
    span: 7
  collapsible: true
  collapsed: false
  backgroundColor: "rgba(45, 27, 84, 0.7)"

# WIDGETS IN DATA GROUP
linkwarden-link:
  type: "link"
  group: "data-group"
  name: "Linkwarden"
  url: "https://linkwarden.squirrel-corn.ts.net"
  icon: "bookmark"
  description: "Bookmark & Link Management"
  statusCheck: true

archivebox-link:
  type: "link"
  group: "data-group"
  name: "ArchiveBox"
  url: "https://archivebox.squirrel-corn.ts.net"
  icon: "archive"
  description: "Web Page Archiving"
  statusCheck: true

trilium-link:
  type: "link"
  group: "data-group"
  name: "Trilium"
  url: "https://trilium.squirrel-corn.ts.net"
  icon: "notes"
  description: "Hierarchical Note Taking"
  statusCheck: true

radar-widget:
  type: "widget"
  widget: "radar"
  position:
    row: 4
    column: 8
    span: 5
  config:
    location: "30033"
    displayName: "Decatur, GA"
    apiKey: "a8ef47eaa6bec9780dad5ad07c880c61"

system-group:
  type: "group"
  title: "System Management"
  position:
    row: 5
    column: 1
    span: 6
  collapsible: true
  collapsed: false
  backgroundColor: "#2d1b54"

# WIDGETS IN SYSTEM GROUP  
pihole-link:
  type: "link"
  group: "system-group"
  name: "Pi-hole"
  url: "https://pihole.squirrel-corn.ts.net/admin"
  icon: "shield"
  description: "Network-wide Ad Blocking & DNS"
  statusCheck: true

vaultwarden-link:
  type: "link"
  group: "system-group"
  name: "Vaultwarden"
  url: "https://vaultwarden.squirrel-corn.ts.net"
  icon: "vault"
  description: "Password Manager (Bitwarden)"
  statusCheck: true

# RECENT ACTIVITY - Right before footer
recent-activity-group:
  type: "group"
  title: "Recent Activity"
  position:
    row: 6
    column: 1
    span: 12
  collapsible: false
  collapsed: false
  backgroundColor: "#2d4a22"

# WIDGETS IN RECENT ACTIVITY GROUP
linkwarden-preview:
  type: "preview"
  group: "recent-activity-group"
  config:
    service: "linkwarden"
    title: "Recent Linkwarden Bookmarks"
    limit: 3
    baseUrl: "https://linkwarden.squirrel-corn.ts.net"
    apiKey: "eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..uY-N-_RUfpXPKNpQ.k1rKCgkgUhwyLlpIbfVEvvFv0HvBPp5nWznFwE7Az0LOaN_D3IiQleUL8N0G0uw0m3s5Lf6j7u_v3LNy2iCCLTl7QCyvvk20sDXyBXCUHouavkiK8F8j.ENi8pz_0NS24cUoZpYCq5g"

trilium-preview:
  type: "preview"
  group: "recent-activity-group"
  config:
    service: "trilium"
    title: "Recent Trilium Notes"
    limit: 3

obsidian-preview:
  type: "preview"
  group: "recent-activity-group"
  config:
    service: "obsidian"
    title: "Recent Obsidian Notes"
    limit: 3

# FOOTER ROW
footer-info:
  type: "widget"
  widget: "motd"
  position:
    row: 7
    column: 1
    span: 9
  backgroundColor: "rgba(0, 0, 0, 0.2)"
  config:
    title: "Slate Dashboard"
    message: "Open-source personal dashboard • Built with ❤️ • Self-hosted & customizable"
    icon: "⚡"
    priority: "low"
    dismissible: false
    timestamp: false

footer-theme-switcher:
  type: "widget"
  widget: "theme-switcher"
  position:
    row: 7
    column: 10
    span: 3
  backgroundColor: "rgba(0, 0, 0, 0.2)"
  config:
    availableThemes: ["dark", "light", "retro", "synthwave", "tokyo-night"]